name: Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: echo Hello, world!

      - name: Send mail
        if : always()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
         # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
         # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: fasireddy@gmail.com
          # from email name
          from: veera
